apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-first-deployment
  labels:    
    type: front-end
spec:
  template:
    metadata:
     name: my-first-app2
     labels:
      app: hello
      env: production
      type: front-end
    spec:
     containers:
      - name: nginx
        image: nginx  
  
  replicas: 3
  
  selector:
    matchLabels:
      type: front-end
    