apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    name: myapp
    type: front-end
spec:
  template:
    metadata:
      name: my-first-app2
      labels:
        app: hello
        env: production
        type: front-end
    spec:
      containers:
        - name: nginx
          image: nginx    
  selector:
    matchLabels:
      type: front-end
  replicas: 3


    





      

