apiVersion: v1
kind: Pod
metadata:
  name: my-second-app
  labels:
    app: different
    tire: production
    type: front-end
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - sleep
        - "3600"
  restartPolicy: Always